[feat] timeline 페이지를 아래로 잡아내리면 갱신되는 기능 추가
software-maestro-starting-blue/fourtooncookie-frontend pull request #42
Opened 2024-09-07 16:47 UTC by SproutMJ

### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-292
---
* 구현 내용
타임라인 화면을 끌어내리면 갱신되는 기능 추가
onfreshing, reached 변수를 각각 두어 useEffect가 새로고침할 때와 무한스크롤할 때에 대한 감지를 나눠 서로 꼬이는 문제를 해결
이때, 새로고침하는 useEffect에서 page도 감지하는 이유는 page가 0으로 되지 않은 채로 새로고침되는 현상이 발견되어 refreshing && page === 0 조건이 되야 동작하도록 하기 위함

* 추가 발생한 문제(논의 사항)

### 화면 예시
---

https://github.com/user-attachments/assets/a3ab1d04-fdca-4b95-93d6-cfb3e338105e

2024-09-08 11:02 UTC, JuneBridge03 requested changes
추가적인 기능을 구현하시느라 너무 수고 많으셨습니다..!

다만, 기존 코드 베이스로 기능을 추가하면서 발견되는 문제들이 보이다보니 수정이 조금 많이 필요해보입니다..! 의견을 드리니 참고해주시면 감사하겠습니다!

2024-09-08 11:02 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +            paintingImageUrls: diary.paintingImageUrls.length ? diary.paintingImageUrls : diaryDefaultImages
DiaryTimelinePage\DiaryComponent\DiaryPaintingImagesLayout의 코드 (https://github.com/software-maestro-starting-blue/fourtooncookie-frontend/blob/develop/fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/DiaryPaintingImagesLayout/DiaryPaintingImagesLayout.tsx)

를 확인해보시면, paintingImageUrls.length를 통해 일기가 전부 그려졌는가를 판단합니다.

그러나, 현재와 같이 default로 대체하는 로직이 들어가게 되면 일기가 항상 전부 그려진 것처럼 나타난다는 문제가 발생할 것이라고 생각합니다.

따라서 paintingImageUrls가 온전하지 않더라도 default 이미지로 대체할 필요는 없다고 생각합니다.

(곧, 현재의 로직을 유지하실 계획이시라면 return result;로 해도 될 것 같다는 말씀을 드립니다.)

2024-09-08 11:04 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +                setHasMore(true);
항상 hasMore이 true이지 않을 수도 있다는 생각이 듭니다..!

(반례, 사용자가 일기 쓴 것이 하나도 없어서 result = null인 경우?)

2024-09-09 01:52 UTC, SproutMJ commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +    const onRefresh = async () => {
변경 했습니다!

2024-09-09 02:00 UTC, SproutMJ commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +    const [reached, setReached] = useState(false);
ref를 사용하고 status를 enum으로 합쳤습니다.
isRefreshing, isReached는 필요가 없어져서 제거되었습니다

2024-09-09 02:02 UTC, SproutMJ commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +        setHasMore(true);
ref를 사용하여 리렌더링을 줄이고 useEffect 내부에서 status가 none이면 로직을 중단시키도록 하였습니다.

2024-09-09 02:02 UTC, SproutMJ commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +    }, [reached]);
작성해주신 코드 너무 감사합니다...! 준교님이 코드를 잘 작성해주셔서 해당 로직을 토대로 작성하게 되었습니다

2024-09-09 02:04 UTC, SproutMJ commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +            paintingImageUrls: diary.paintingImageUrls.length ? diary.paintingImageUrls : diaryDefaultImages
해당 부분 제거하여 getDiaries에서 가져온 값을 바로 사용하게 변경했습니다

2024-09-09 02:05 UTC, SproutMJ commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +                setHasMore(true);
데이터 조회를 마지막에 두고 그 과정에서 데이터가 없으면 hasMore가 false가 되도록 변경했습니다

2024-09-09 02:23 UTC, JuneBridge03 approved these changes
리뷰 반영된 부분 전부 확인하였습니다! 감사합니다!

2024-09-09 04:48 UTC, minseojo approved these changes

2024-09-09 04:48 UTC, merged