feat: 일기 이미지 다운로드, 공유 기능
software-maestro-starting-blue/fourtooncookie-frontend pull request #72
Opened 2024-09-23 14:34 UTC by minseojo

### [feat] 일기 이미지 다운로드, 공유 기능(카카오톡)
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-380
---
* 구현 내용

* 추가 발생한 문제(논의 사항)
새로운 의존성 떄문에 빌드를 다시 해야함

2024-09-24 05:23 UTC, SproutMJ reviewed
빠른 시간안에 구현 정말 감사합니다. 몇가지만 남겨놓으니 확인 부탁드려요

2024-09-24 05:23 UTC, SproutMJ commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/Footer/Footer.tsx
> +        } catch (error: any) {
여기에 any를 사용하는 부분이 있네요 지양하는 편이 좋을 듯 한데 어떤가요?

2024-09-24 05:45 UTC, SproutMJ commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/Footer/Footer.tsx
> +            }
이런곳에 평문이 많이 존재하는데 상수화하면 좋을 듯 합니다

2024-09-24 06:08 UTC, JuneBridge03 requested changes
Native 환경에서 개발이 쉽지 않음에도 개발해주셔서 너무 감사드립니다.

다만, 다음과 같이 수정하면 좋을만한 부분이 있어서 해당 부분을 서술해두니 참고해주시면 감사하겠습니다.

2024-09-24 06:08 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/Footer/Footer.tsx
> +            const fileUri = await getDiaryImage(diaryId);
현재는 api method를 바로 callin하는 형태로 진행하셨지만, 아시다싶이 이제 react query를 활용하기로 정책을 정했기에 차라리 다음과 같은 query custom hook을 제작하시는 것도 좋을 것 같습니다.
특히, react query로 훅을 제작하시는 것이 

src/hooks/server/diary.ts
```typescript
const useDiaryFullImage(diaryId: number, enabled: boolean){
    return useQuery(['diary', diaryId, 'fullimage'], () => getDiaryImage(diaryId), {
        enabled: enabled
    };
}
```

현 컴포넌트
```typescript

enum ImageActionState {
    NONE, DOWNLOAD, SHARE
}

(...)

const [ imageActionState, setImageActionState ] = useState<ImageActionState>(ImageActionState.NONE);
const { data: imageUri } = useDiaryFullImage();

useEffect(() => {
   if (imageActionState == ImageActionState.NONE) return;
   
   ( ... imageActionState에 따른 download, share 로직 수행 ... )

   setImageActionState(ImageActionState.NONE);
}, [imageActionState, imageUri]);

const handleDownload = () => setImageActionState(ImageActionState.DOWNLOAD);

const handleShare = () => setImageActionState(ImageActionState.SHARE);

```

2024-09-24 06:33 UTC, minseojo commented on fourtoon-cookie/src/apis/diary.ts
> +    const response = await requestApi(`/diary/${diaryId}/download`, API_METHOD_TYPE.GET);
넵 restful 하기 위해 `/diary/{diaryId}/image/full`이 좋은 것 같습니다!

2024-09-30 05:48 UTC, JuneBridge03 approved these changes

2024-09-30 05:51 UTC, SproutMJ approved these changes

2024-09-30 05:51 UTC, merged